spring.application.name=AirBnb
#DB config
spring.datasource.url=jdbc:postgresql://localhost:5432/airBnb
spring.jpa.hibernate.ddl-auto=create-drop
//update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.username=postgres
spring.datasource.password=****@***
server.servlet.context-path=/api/v1
jwt.secretKey=mySuperSecretKeyForJWTAuthentication12345
frontend.url=http://localhost:8080
stripe.secret.key=sk_test_51N8sXoKZy7n9mLh5u